version: '3.8'

services:
  invoicing-api:
    image: invoicing-api
    build:
      context: .
      dockerfile: src/Invoicing.Api/Dockerfile
    ports:
      - "5000:8080"
    environment:
      ConnectionStrings__InvoicingDb: "Server=mssql,1433;Database=InvoicingDb;User Id=sa;Password=YourStrong@Password!;Encrypt=False;"
    depends_on:
      mssql:
        condition: service_healthy
      mssql-init:
        condition: service_completed_successfully
    networks:
      - invoicing-app-network
      
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong@Password!"
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S mssql -U sa -P "YourStrong@Password!" -Q "SELECT 1" -N -C
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
    volumes:
      - ./mssql/backups:/var/opt/mssql/backups
      - ./mssql/data:/var/opt/mssql/data
      - ./mssql/log:/var/opt/mssql/log
    networks:
      - invoicing-app-network
  
  mssql-init:
    image: mcr.microsoft.com/mssql-tools:latest
    command: "/opt/mssql-tools/bin/sqlcmd -S mssql -l 60 -U sa -P 'YourStrong@Password!' -d master -i /tmp/init-db.sql"
    depends_on:
      mssql:
        condition: service_healthy
    volumes:
      - ./db-scripts/init-db.sql:/tmp/init-db.sql
    networks:
      - invoicing-app-network

networks:
  invoicing-app-network:
    driver: bridge
